_target_: src.models.classifier_module.ClassifierModule
backbone: src.models.vicreg_module.VICRegModule.getBackbone
num_classes: src.models.birds_datamodule.BirdsDataModule.num_classes
max_epochs: 100