_target_: src.models.classifier_module.ClassifierModule
backbone_ckpt_path: "${paths.output_dir}/models/best_model_vicreg.ckpt"
num_classes: src.models.birds_datamodule.BirdsDataModule.num_classes
max_epochs: 100