_target_: src.models.classifier_module.ClassifierModule
backbone_ckpt_path: "${paths.checkpoint_dir}best_model_vicreg.ckpt"
ssl_backbone: False
backbone_pretrained: False
freeze: False
num_classes: 525
max_epochs: 100