_target_: src.models.classifier_module.ClassifierModule
backbone_ckpt_path: "${paths.checkpoint_dir}best_model_vicreg.ckpt"
ssl_backbone: True
backbone_pretrained: True
freeze: True
num_classes: 525
max_epochs: 100

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.simple_dense_net.SimpleDenseNet
  input_size: 512
  lin1_size: 64
  lin2_size: 128
  lin3_size: 64
  output_size: 525 # num_classes