defaults:
  - default
  - _self_


# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html
model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.checkpoint_dir} # directory to save the model file
  filename: 'best_model_with_ssl_not_frozen_classifier' # checkpoint filename
  monitor: 'val_acc' # name of the logged metric which determines when model is improving
  mode: "max"

early_stopping:
  monitor: "val_acc"
  patience: 100
  mode: "max"