defaults:
  - default
  - _self_


# https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html
model_checkpoint:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: $'{paths.output_dir}/models' # directory to save the model file
  filename: 'best_model_with_classifier' # checkpoint filename
  monitor: 'val_acc' # name of the logged metric which determines when model is improving