# @package _global_

defaults:
  - _self_
  - data: classifier # choose datamodule with `test_dataloader()` for evaluation
  - model: classifier
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: "${paths.output_dir}/models/best_model_with_classifier.ckpt"
