# @package _global_

defaults:
  - _self_
  - data: classifier # choose datamodule with `test_dataloader()` for evaluation
  - model: classifier_ssl_frozen
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: "${paths.checkpoint_dir}best_model_with_ssl_frozen.ckpt"
